#!/usr/bin/env bash

function main {
  local BUILD_DIR="$1"; shift
  local CACHE_DIR="$1"; shift
  local ENV_DIR="$1"; shift

  local ver_python="$(pyenv version | awk '{print $1}')"
  local fl_first_time=

  local tmp_versions="${BOARD_PATH}/work/pyenv/vendor/pyenv/versions"
  local pth_python_cache="${DATA}/cache/pyenv/${ver_python}-${ID_INSTALL}.tgz"

  if [[ ! -d "${tmp_versions}/${ver_python}" ]]; then
    fl_first_time=1
  elif [[ ! -f "$pth_python_cache" ]]; then
    fl_first_time=1
  fi

  if [[ -f "$pth_python_cache" ]]; then
    (cd "${tmp_versions}" && gtar xfz "$pth_python_cache")
    pyenv rehash
  else
    pyenv install -s
    pyenv rehash
    pip install pipenv 
    pyenv rehash
  fi

  if [[ -n "$fl_first_time" ]]; then
    mkdir -p "${DATA}/cache/pyenv"
    (cd "${tmp_versions}" && gtar cfz "$pth_python_cache" "${ver_python}")
  fi

  pyenv rehash
}

source sub "$0" "$@"
