#!/usr/bin/env bash

function main {
  local BUILD_DIR="$1"; shift
  local CACHE_DIR="$1"; shift
  local ENV_DIR="$1"; shift

  set -x

  local ver_python="$(pyenv local)"
  local fl_first_time=

  local tmp_versions="${BOARD_PATH}/work/pyenv/vendor/pyenv/versions"
  local pth_python_cache="${DATA}/cache/pyenv/${ver_python}-${ID_INSTALL}.tgz"

  mkdir -p "${tmp_versions}"

  if [[ -f "$pth_python_cache" ]]; then
    (cd "${tmp_versions}" && gtar xfz "$pth_python_cache")
    pyenv rehash
  else
    pyenv install -s
    pyenv rehash
    pip install pipenv=="${PIPENV_VERSION}"
    pyenv rehash

    mkdir -p "${DATA}/cache/pyenv"
    (cd "${tmp_versions}" && gtar cfz "$pth_python_cache" "${ver_python}")
  fi

  pip install pip=="${PIP_VERSION}"
  pip install pipenv=="${PIPENV_VERSION}"
  pyenv rehash
}

source sub "$0" "$@"
