#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  git clone -b "v${PYTHON_ENV_VERSION}" git@github.com:pyenv/pyenv "$shome/vendor/pyenv-${PYTHON_ENV_VERSION}" || true
  rm -rf "$shome/vendor/pyenv"
  ln -nfs "pyenv-${PYTHON_ENV_VERSION}" "$shome/vendor/pyenv"
}

main "$@"
