#!/usr/bin/env bash

function _pyenv_profile {
  local shome="${_pyenv_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  export PYENV_ROOT="$shome/vendor/pyenv"
  PATH="$shome/bin:${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:$PATH"
}

_pyenv_profile
