#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_pyenv="0.0.1"
  jq -n --arg pyenv "$ver_pyenv" '{pyenv: $pyenv}'
}

version "$@"
